### ISSUE TITLE
render_autoindex('.') not working in 0.6.6

### ISSUE THREAD

**Issue by Raffa87** [general03/flask-autoindex#57] opened 2020-08-06 07:27 UTC
Dear developers,
first of all, thank you very much for this useful library!

We used the version 0.6.4 without issues, but now, using the version 0.6.6, we are experiencing a problem on the method render_autoindex('.') (that was working on the old version)
Is something changed in the syntax? Could you suggest something in particular in the documentation?

Thank you very much for all your support and all your work

**Comment by general03** [comment] 2020-08-27 13:50
Hi,

Can you put you code because I can't reproduce this issue

Thanks

**Comment by general03** [comment] 2020-10-21 13:10
Without answer I close this issue

**Closed as completed by general03** 2020-10-21 13:10 UTC
